version: 2

sources:
  - name:  raw
    schema: gz_raw_data 
    tables:
      - name: sales
        identifier:  ventes_gz_brutes
      - name: product
        identifier: produit_brut_gz
      - name: ship
        identifier: raw_gz_ship